asm
tcheremkhina/first-term pull request #1
Opened 2020-06-28 08:58 UTC by tcheremkhina

2020-06-28 22:29 UTC, kt-cpp commented on asm/sub.asm
> +                jmp             .r
Обычно такое делается через ```sbb```, но так как здесь решение, которое выводит вычитание по модулю и такая самописная штука, то пусть будет так

2020-06-28 22:31 UTC, kt-cpp commented on asm/mul.asm
> +                push            rdi
Зачем пушить ```rdi``` если все равно его портишь

2020-06-28 22:36 UTC, kt-cpp commented on asm/mul.asm
> +;   [rdi] = [rdi] * [rsi]
Неявным аргументом к этой функции является ```r11```, где ты хранишь зарезервированное пространство для вычислений

И ответ на самом деле тоже зарезервирован

И почему нельзя портить стэк в этой функции для ```tmp``` переменной? Кажется это просто

2020-06-28 23:17 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 256
Тесты расчитаны на 128 разрядов * 128 разрядов, поэтому они не видят ошибку, а я вижу

Умножение пока что не рабочее (фиксится удалением одной пары строчек, думаю найдете :)

2020-06-28 23:18 UTC, kt-cpp commented on asm/mul.asm
> +;   r12 -- length of numbers in qwords
А давайте ```rcx``` для консистентности

2020-06-28 23:19 UTC, kt-cpp requested changes
Есть много мелочей, но пока что они опущены, потому что умножение не рабочее

2020-07-01 15:27 UTC, tcheremkhina commented on asm/mul.asm
> +;   [rdi] = [rdi] * [rsi]
Непонятно что требуется в этом комментарии. 
В третьем замечании непонятно о чем речь.

2020-07-01 18:40 UTC, kt-cpp commented on asm/mul.asm
> +;   [rdi] = [rdi] * [rsi]
Про третье: почитай про стековый фрейм и как выделяются локальные переменные на стеке. Подумай о том, можно ли сделать твой tmp буффер локальной переменной.

Первые два замечания видимо понятны

Требуется: написать так, чтобы когда я посмотрел на контракт функции - я понял, что и в какие регистры мне положить. И мне не хочется класть еще что-то дополнительное - связанное с твоими вычислениями внутри функции (tmp буффер).

2020-07-03 11:13 UTC, tcheremkhina commented on asm/mul.asm
> +                push            rdi
fixed

2020-07-03 11:14 UTC, tcheremkhina commented on asm/mul.asm
> +;   [rdi] = [rdi] * [rsi]
вроде fixed

2020-07-03 11:14 UTC, tcheremkhina commented on asm/mul.asm
> +                mov             rcx, 256
fixed

2020-07-03 11:14 UTC, tcheremkhina commented on asm/mul.asm
> +;   r12 -- length of numbers in qwords
fixed

2020-07-03 13:00 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 256
`rcx` портится после выхода из этой функции

2020-07-03 13:00 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 256
И он никак в этой строчке не зависит от входного `rcx`

2020-07-03 13:01 UTC, kt-cpp commented on asm/mul.asm
> +                sub             rsp, 2 * 256 * 8
А не многовато ли доппамяти?

2020-07-03 13:03 UTC, kt-cpp requested changes
Памяти использовано `5 * 256 * 8` байт, чтобы считать два 128 разрядных числа, перемножить их и вывести 256р ответ

Можно сократить почти в 2 раза (`mul_long_short` даст тебе максимум на один разряд больше, и хранить входные числа как 256р слишком overhead)

2020-07-03 22:56 UTC, tcheremkhina commented on asm/mul.asm
> +                mov             rcx, 256
Теперь зависит от входного

2020-07-03 22:56 UTC, tcheremkhina commented on asm/mul.asm
> +                sub             rsp, 2 * 256 * 8
Исправила

2020-07-04 16:59 UTC, lejabque commented
Выглядит так, как будто после ребейза из upstream ты сделала `git push -f origin asm` раньше, чем `git push -f origin master`.
Попробуй сделать так:
```
git checkout asm
git rebase -i HEAD~20
// откроется текстовый редактор стандартный, в нём нужно у всех коммитов, которые должны быть в мастере (сделаны не тобой) поменять pick на d, затем сохранить этот файл и выйти из него
git push -f origin asm
git rebase master
git push -f origin asm
```

После этого, по идее, должно всё стать норм, если не получится, то телеграм @lejabq

2020-07-05 18:48 UTC, kt-cpp approved these changes
Ок.

2020-07-05 18:48 UTC, merged