bigint-opt
tcheremkhina/first-term pull request #4
Opened 2020-09-04 14:19 UTC by tcheremkhina

2020-09-20 21:37 UTC, kt-cpp requested changes

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/my_vector.h
> +    explicit my_vector(size_t const& len, uint32_t const& x = 0) {
[minor] Эти типы нет смысла принимать по ссылки, ибо они примитивны и мало, что их копирование ничем не дороже взятия ссылки (т.е. указателя). При это в качестве плюсы получаем на один уровень индирекции меньше

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/my_vector.h
> +        vec = other.vec;
Кажется лучше поменять эти две операции местами ибо если у тебя вторая кинет исключение, то класс будет в каком-то невалидном состоянии

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/my_vector.h
> +        assert(ref_counter);
[minor] Лучше не кастовать интегральные типы к логическим, а просто писать понятные условия с операциями сравнения

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/my_vector.h
> +    std::vector<uint32_t> vec;
Зачем он публичный, если все полезные функции были уже реализованы выше?

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/my_vector.h
> +struct my_vector {
В целом если класс не шаблонный зачем писать реализацию всего в хедере?

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +    static const size_t MAX_STATIC = sizeof(my_vector*) / sizeof(uint32_t);
[minor] `constexpr` ибо текущая конструкция не является гарантированно константой компиляции

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +            std::memcpy(static_vec, other.static_vec, sizeof(static_vec));
[minor] Мы в с++. `std::copy`

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +            }
[minor] `std::fill`

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +            memset(static_vec, 0, sizeof(static_vec));
А зачем это?

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +    buffer(size_t len, uint32_t const& x) {
[minor] Снова замечание про передачу примитивных типов по ссылке

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +        if (*this == other) {
Логическое равенство объектов не говорит о том, что это один и тот же объект в памяти. А тебя здесь интересует именно второе

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +        }
Не очень понимаю смысл этой конструкции. Выглядит как какой-то странный частный случай

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +            std::memcpy(static_vec, other.static_vec, sizeof(static_vec));
[minor] `std::copy`

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +    }
Выглядит как куча лишних копированиq в случае small

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +            memset(static_vec, 0, sizeof(static_vec));
[minor] `std::fill` и зачем на весь вектор?

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +    void unshare() {
Почему эта функция публичная?

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +    uint32_t size() const {
Мб `size_t`?

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +            }
У вектор для таких случаев есть конструктор от двух указателей. Однако в данной ситуации его полезно сделать прямо в классе my_vector, чтобы избежать лишних копиований

2020-09-20 21:37 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +    }
Глобально проблема в том, что ты сжимаешь вектор. Дорога не динамическая память, а её выделение. Дальше это такая же опертивка как и стек. Одна ты сейчас просто так отдаёшь с боем полученную память. Плюс если у тебя в вектор размера примерно `MAX_STATIC`, то вставляю и удаляя из него элементы будет происходить куча аллокаций

2020-09-21 21:49 UTC, tcheremkhina commented on bigint-optimized/my_vector.h
> +    explicit my_vector(size_t const& len, uint32_t const& x = 0) {
fixed

2020-09-21 21:49 UTC, tcheremkhina commented on bigint-optimized/my_vector.h
> +        vec = other.vec;
fixed

2020-09-21 21:49 UTC, tcheremkhina commented on bigint-optimized/my_vector.h
> +        assert(ref_counter);
fixed

2020-09-21 21:49 UTC, tcheremkhina commented on bigint-optimized/my_vector.h
> +    std::vector<uint32_t> vec;
fixed

2020-09-21 21:49 UTC, tcheremkhina commented on bigint-optimized/my_vector.h
> +struct my_vector {
теперь в my_vector.cpp

2020-09-21 21:49 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +    static const size_t MAX_STATIC = sizeof(my_vector*) / sizeof(uint32_t);
fixed

2020-09-21 21:49 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +            std::memcpy(static_vec, other.static_vec, sizeof(static_vec));
fixed

2020-09-21 21:49 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +            }
fixed

2020-09-21 21:49 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +            memset(static_vec, 0, sizeof(static_vec));
fixed

2020-09-21 21:49 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +    buffer(size_t len, uint32_t const& x) {
fixed

2020-09-21 21:49 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +        if (*this == other) {
fixed

2020-09-21 21:49 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +        }
Нужно было для отладки. Убрала

2020-09-21 21:50 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +            std::memcpy(static_vec, other.static_vec, sizeof(static_vec));
fixed

2020-09-21 21:50 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +    }
fixed

2020-09-21 21:50 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +            memset(static_vec, 0, sizeof(static_vec));
fixed

2020-09-21 21:50 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +    void unshare() {
fixed

2020-09-21 21:50 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +    uint32_t size() const {
fixed

2020-09-21 21:50 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +            }
fixed

2020-09-21 21:50 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +    }
Больше не перекидываю элементы из `dynamic_vec` в `static_vec`

2020-09-22 22:17 UTC, kt-cpp requested changes

2020-09-22 22:17 UTC, kt-cpp commented on bigint-optimized/my_vector.cpp
> +}
[minor] Даже гихаб подсказывает про перенос в конце файла

2020-09-22 22:17 UTC, kt-cpp commented on bigint-optimized/my_vector.h
> +    friend bool operator== (my_vector const& a, my_vector const& b);
Приватная friend функция. Шта?

2020-09-22 22:17 UTC, kt-cpp commented on bigint-optimized/my_vector.cpp
> +}
* Зачем тут ссылка на указатель?
* У вектора есть конструктор от двух итераторов

2020-09-22 22:17 UTC, kt-cpp commented on bigint-optimized/my_vector.cpp
> +}
Не очень понятно зачем данному классу вообще оператор присваивания да ещё с таким контрактом

2020-09-22 22:17 UTC, kt-cpp commented on bigint-optimized/my_vector.cpp
> +}
У вектора есть конструктор, делающий то, что тут делается через `resize`

2020-09-22 22:17 UTC, kt-cpp commented on bigint-optimized/buffer.cpp
> +    this->~buffer();
[minor] Кажется не обязательно вызывать через `this`

2020-09-22 22:17 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +    explicit buffer(size_t len);
[minor] Можно просто конструктору на 12 строчку передать 0 в качестве дефолтного параметра

2020-09-22 22:17 UTC, kt-cpp commented on bigint-optimized/buffer.cpp
> +        dynamic_vec->push_back(x);
Эта строка в общем случае может просить исключение и мы получим класс в невалидном состоянии

2020-09-22 22:17 UTC, kt-cpp commented on bigint-optimized/buffer.cpp
> +}
У функции resize из `std::vector` (который заменяет ваш класс) не такое поведение, как в данной функции

2020-09-23 21:07 UTC, tcheremkhina commented on bigint-optimized/my_vector.cpp
> +}
fixed

2020-09-23 21:07 UTC, tcheremkhina commented on bigint-optimized/my_vector.h
> +    friend bool operator== (my_vector const& a, my_vector const& b);
fixed

2020-09-23 21:07 UTC, tcheremkhina commented on bigint-optimized/my_vector.cpp
> +}
fixed

2020-09-23 21:07 UTC, tcheremkhina commented on bigint-optimized/my_vector.cpp
> +}
удалила

2020-09-23 21:07 UTC, tcheremkhina commented on bigint-optimized/my_vector.cpp
> +}
fixed

2020-09-23 21:07 UTC, tcheremkhina commented on bigint-optimized/buffer.cpp
> +    this->~buffer();
просто `~buffer();` не компилируется

2020-09-23 21:07 UTC, tcheremkhina commented on bigint-optimized/buffer.h
> +    explicit buffer(size_t len);
fixed

2020-09-23 21:07 UTC, tcheremkhina commented on bigint-optimized/buffer.cpp
> +        dynamic_vec->push_back(x);
fixed

2020-09-23 21:07 UTC, tcheremkhina commented on bigint-optimized/buffer.cpp
> +}
updated

2020-09-23 21:46 UTC, kt-cpp requested changes

2020-09-23 21:46 UTC, kt-cpp commented on bigint-optimized/buffer.cpp
> +        tmp->push_back(x);
Эта строчка может бросить исключение, и `tmp` просто утечёт

2020-09-23 21:46 UTC, kt-cpp commented on bigint-optimized/my_vector.cpp
> +    vec = std::vector<uint32_t> (first, last);
Чем вам так не угодила инициализация членов класса?

2020-09-23 21:46 UTC, kt-cpp commented on bigint-optimized/my_vector.cpp
> +    vec = std::vector<uint32_t> (len, x);
Чем вам так не угодила инициализация членов класса?

2020-09-23 21:46 UTC, kt-cpp commented on bigint-optimized/buffer.cpp
>  }
[note] Можно написать эффективнее, особенно в случае большого `new_size`

2020-09-23 21:54 UTC, tcheremkhina commented on bigint-optimized/buffer.cpp
> +        tmp->push_back(x);
fixed

2020-09-23 21:54 UTC, tcheremkhina commented on bigint-optimized/my_vector.cpp
> +    vec = std::vector<uint32_t> (first, last);
fixed

2020-09-23 21:54 UTC, tcheremkhina commented on bigint-optimized/my_vector.cpp
> +    vec = std::vector<uint32_t> (len, x);
fixed

2020-09-24 12:04 UTC, dzhiblavi approved these changes

2020-09-24 12:07 UTC, kt-cpp approved these changes

2020-09-24 12:07 UTC, merged